# Generated by Django 2.1.2 on 2018-10-31 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(db_column='Genre_ID', primary_key=True, serialize=False)),
                ('genre_name', models.CharField(blank=True, db_column='Genre_Name', max_length=250, null=True)),
            ],
            options={
                'db_table': 'Genre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(db_column='Movie_ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=250)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('director', models.CharField(blank=True, db_column='Director', max_length=250, null=True)),
                ('rating', models.FloatField(blank=True, db_column='Rating', null=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Movie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('comment_id', models.AutoField(db_column='Comment_ID', primary_key=True, serialize=False)),
                ('comments', models.CharField(blank=True, db_column='Comments', max_length=1000, null=True)),
                ('score', models.IntegerField(blank=True, db_column='Score', null=True)),
            ],
            options={
                'db_table': 'Rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=250)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=250, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GenreMovie',
            fields=[
                ('genre', models.ForeignKey(db_column='Genre_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movie.Genre')),
                ('movie', models.ForeignKey(db_column='Movie_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='movie.Movie')),
            ],
            options={
                'db_table': 'Genre_Movie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RateMovie',
            fields=[
                ('comment', models.ForeignKey(db_column='Comment_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movie.Rating')),
                ('movie', models.ForeignKey(db_column='Movie_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='movie.Movie')),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='movie.User')),
            ],
            options={
                'db_table': 'Rate_Movie',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='genremovie',
            unique_together={('genre', 'movie')},
        ),
    ]
